name: Publish Go Module

on:
  push:
    branches:
      - master

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16 # Choose the Go version you need

      - name: Authenticate with GitHub
        run: echo "//golang.org/x/oauth2 git https://github.com/golang/oauth2" >> ~/.netrc

      - name: Publish to Go Module Proxy
        run: |
          git config --global user.email "suhas.g@cashfree.com"
          git config --global user.name "Suhas Cashfree"
          go mod tidy
          GOPROXY=proxy.golang.org go list -m github.com/suhas-cashfree/golangsum@v0.0.13
        env:
          GOPROXY: proxy.golang.org
